### ISSUE TITLE
Some feedback on my user experience

### ISSUE THREAD

**Issue by jorroll** [std-proposal/temporal#4]
Hi there,

I maintain a javascript recurring dates/schedule library, [rSchedule](https://gitlab.com/john.carroll.p/rschedule), which happens to be date library agnostic (i.e. it supports `moment`, `luxon`, and standard `Date`). For fun, I decided to try implementing a date adapter for this temporal polyfill and running it against my tests. Eventually I realized that the version of this polyfill on NPM is pretty behind the version in this repo. That alone would have stopped my experiment.

Even basing my implementation of the code in this repo though, I ended up giving up when it became apparent that I was going to need to do more work than I realized. A few annoying aspects of the current polyfill's API:

- Can't simply call `new CivilDateTime()` like `new Date()` to get an object with the current local clock's values.
- Can't simply call `new ZonedDateTime()` like `new Date()` to get an object with the current local clock's values & the current timezone.
- Neither `CivilDateTime` nor `ZonedDateTime` have a `fromObject()` static method to simplify the creation of new `CivilDateTime` / `ZonedDateTime`.
  - Can't do `ZonedDateTime.fromObject({year: 2019, month: 10, day: 10, timeZone: 'America/Los_Angeles'})`
- No `valueOf()` method on `ZonedDateTime` to quickly compare `ZoneDateTime` to `Date`.
  - Similarly, it's unclear how comparison's between `CivilDateTime` objects should be handled. Using `CivilDateTime#difference()` seems heavy handed.
- Nothing like `Date#toISOString()` on `ZoneDateTime` to see what the value looks like in UTC.

Also another annoyance which may not be universally applicable, but in my case I'm using both `CivilDateTime` and `ZonedDateTime` together. Having `ZonedDateTime` implement `getCivilDateTime()` but not having `CivilDateTime` implement it means that I need to check what type of object I'm dealing with, rather than simply call `date.getCivilDateTime()` and know that I've got a `CivilDateTime`. Similarly, I can't call `withZone()` on a `ZonedDateTime` to change the zone and/or quickly assure myself that I'm working with a `ZonedDateTime` in the proper zone.

While I didn't have cause to explore the other objects associated with the `temporal` module, it appears that they behave similarly. In general, I think the API could be improved by normalizing the interfaces between objects, even when that means `CivilDateTime#getCivilDateTime()` simply returns the same object. Not sure if this will be a general feeling though.

**Comment by jorroll** [comment]
PS: If any of this feedback isn't applicable to the current spec text, feel free to ignore.

**Comment by pipobscure** [comment]
Thank you very much!!! This is really helpful. Your feedback will be incorporated where sensible.

I'll close this, since you have already copied over to the spec-proposal. Thanks again!
