### ISSUE TITLE
Implementation is too slow

### ISSUE THREAD

**Issue by ferk6a** [std-proposal/temporal#5]
Hello! I absolutely adore this specification and I'm eager to use it in production environments. Last time I checked on this proposal, the repo was https://github.com/pipobscure/tc39-proposal-temporal, so I have made one PR there to improve some stuff: https://github.com/pipobscure/tc39-proposal-temporal/pull/3, so I think I will split the problems in different issues.

One big problem is that `plus` works using a `while` loop which actually isn't optimized. And it is *very* slow. I don't know in depth how real Date implementations handle this issue, perhaps with pre-calculated tables, but it certainly helps to use modulo instead of while loops, so that's what I did in my previous implementation.

In my implementation you can check [this test](https://github.com/pipobscure/tc39-proposal-temporal/blob/2827eeff5b0e9165acd45a99d1c02481474a5330/test/shared.mjs#L108-L147) which takes ages to complete with while loops.

This is however in the previous implementation. I've written new ones for this new implementation which I can submit a PR for:
```javascript

    const mytest = new OffsetDateTime(Instant.fromString('1970-01-01T00:00:00.000000000Z'), '+00:00');
    it('should work', ()=>{ equal(`${mytest.plus({ seconds: Number.MAX_SAFE_INTEGER / 1E6 })}`, '2255-06-05T23:47:34.000000000+00:00'); });
    it('should work', ()=>{ equal(`${mytest.plus({ milliseconds: Number.MAX_SAFE_INTEGER / 1E6 })}`, '1970-04-15T05:59:59.254000000+00:00'); });
    it('should work', ()=>{ equal(`${mytest.plus({ microseconds: Number.MAX_SAFE_INTEGER / 1E3 })}`, '1970-04-15T05:59:59.254740000+00:00'); });
    it('should work', ()=>{ equal(`${mytest.plus({ nanoseconds: Number.MAX_SAFE_INTEGER })}`, '1970-04-15T05:59:59.254740991+00:00'); });
```

This is very important to get right because the conversion of `Date` into temporal can happen using `getTime()`.

**Comment by ferk6a** [comment]
I'm hacking into this. While doing it, I see that the `calculate` code is repeated three times over the codebase (and this leads to bugs, there is already one in `CivilDateTime`!), it was a bit better in the previous implementation. Regardless, it's looking much better in terms of performance now :)

**Comment by pipobscure** [comment]
The implementation is likely to change significantly. As will the API (as in it's already being changed as we speak). However going with Modulo rather than while will be a good idea no matter what.
